ports:
- port: 8000
  onOpen: open-preview
tasks:
- init: >
    pip install -r requirements.txt &&
    python manage.py makemigrations &&
    python manage.py migrate &&
    echo "from django.contrib.auth import get_user_model; get_user_model().objects.create_superuser('admin', '', 'changeme')" | python manage.py shell
  command: >
    python manage.py runserver 0.0.0.0:8000