# Generated by Django 3.0.6 on 2020-06-16 16:52

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200616_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='announcements',
            field=wagtail.core.fields.StreamField([('announcement', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('type', wagtail.core.blocks.ChoiceBlock(choices=[('info', 'danger')])), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'h5', 'ol', 'ul', 'hr', 'link', 'document-link'], help_text='text', required=True))]))], blank=True),
        ),
    ]
